@baseUrl=http://localhost:8003

### get
GET {{baseUrl}}

### create
POST {{baseUrl}} HTTP/1.1
Content-Type: application/json

{
    "data": "hallo"
}

### delete
DELETE {{baseUrl}}

### update
PUT {{baseUrl}}